import React from 'react';
import '../styles/MOTD.scss';

const WITTY_PHRASES = [
  "IT'S ALWAYS DNS.",
  "HAVE YOU TRIED TURNING IT OFF AND ON AGAIN?",
  "THERE IS NO CLOUD, JUST OTHER PEOPLE'S COMPUTERS.",
  "WORKS ON MY MACHINE ¯\\_(ツ)_/¯",
  "A SQL QUERY WALKS INTO A BAR, WALKS UP TO TWO TABLES, AND ASKS: 'CAN I JOIN YOU?'",
  "THE CODE IS THE DOCUMENTATION.",
  "I DON'T ALWAYS TEST MY CODE, BUT WHEN I DO, I DO IT IN PRODUCTION.",
  "DNS IS LIKE THE ARCHITECT FROM THE MATRIX. IT'S RESPONSIBLE FOR EVERYTHING BUT NO ONE KNOWS WHAT IT ACTUALLY DOES.",
  "99 LITTLE BUGS IN THE CODE. 99 LITTLE BUGS. TAKE ONE DOWN, PATCH IT AROUND. 127 LITTLE BUGS IN THE CODE.",
  "PROGRAMMER: AN ORGANISM THAT TURNS COFFEE INTO CODE.",
  "COMPUTERS ARE FAST; PROGRAMMERS ARE TIGHT.",
  "TO ERR IS HUMAN, TO REALLY FOUL THINGS UP REQUIRES A COMPUTER.",
  "REAL PROGRAMMERS DON'T DOCUMENT. IF IT WAS HARD TO WRITE, IT SHOULD BE HARD TO UNDERSTAND.",
  "IF AT FIRST YOU DON'T SUCCEED, CALL IT VERSION 1.0.",
];

export const MOTD: React.FC = () => {
  const [phrase] = React.useState(() => WITTY_PHRASES[Math.floor(Math.random() * WITTY_PHRASES.length)]);

  return (
    <div className="motd">
      <div className="motd__header">MESSAGE_OF_THE_DAY [SYSTEM_CORE]</div>
      <div className="motd__content">
        "{phrase}"
      </div>
      <div className="motd__footer">
        * AUTHORIZED ACCESS ONLY. OPERATOR DISCRETION ADVISED. *
      </div>
    </div>
  );
};
